server:
  port: 8087

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:mysql://mariadb:3306/smart_opd_patient
    username: smartopd
    password: smartopd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: patient-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

jwt:
  secret: 1f94a95c6b83a5d8df4c74b0d785f4787dfb4b16ddc9e0d7df4b8a15ef8b9f7c

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"